### Login to get token
POST http://localhost:5000/api/v1/auth
Content-Type: application/json

{
  "username": "root",
  "password": "rootpassword"
}

### Create Sensor
POST http://localhost:5000/api/v1/networks/TEST01/gateways/00:00:00:00:00:01/sensors
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "macAddress": "22:33:44:55:66:77",
  "name": "Test Sensor",
  "description": "VS Code Test",
  "variable": "temperature",
  "unit": "C"
}

### Get All Sensors
GET http://localhost:5000/api/v1/networks/TEST01/gateways/00:00:00:00:00:01/sensors
Authorization: Bearer {{TOKEN}}

### Delete Sensor
DELETE http://localhost:5000/api/v1/networks/TEST01/gateways/00:00:00:00:00:01/sensors/22:33:44:55:66:77
Authorization: Bearer {{TOKEN}}
